#!/bin/bash

curl -Lo ./kind https://github.com/kubernetes sigs/kind/releases/download/v0.7.0/kind-$(uname)-amd64
sudo chmod +x ./kind
sudo mv ./kind /usr/local/bin/kind
kind version
kind create cluster --loglevel debug --wait=5m